### ISSUE TITLE
please update the mod to 1.19.4

### ISSUE THREAD

**Issue by TechPro424** [henkelmax/replay-voice-chat#11]
**Bug description**
Game crashes on 1.19.4 with this error message: 
```
Replace mod 'Replay Voice Chat' (replayvoicechat) 1.19.2-1.2.3 with any version that is compatible with:
minecraft 1.19.4
voicechat 1.19.4-2.3.28
```

**Steps to reproduce the issue**
1. Install latest version of Simple Voice Chat for 1.19.4 and latest version of this mod from Modrinth
2. Launch the game
3. Game crashes with error.

**Expected behavior**
Game launches and works fine

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue.
https://mclo.gs/Q7HVQL0

**Versions**
- Minecraft version: 1.19.4
- Fabric version: 0.14.17
- Simple Voice Chat version: voicechat 1.19.4-2.3.28
- ReplayMod Version 1.19.2-2.6.9
- Mod version replayvoicechat 1.19.2-1.2.3

**Other mods**
Fabric API latest

**Comment by henkelmax** [comment]
Replay mod hasn't yet been updated for 1.19.4
