### ISSUE TITLE
Incompatible with newest replay mod and simple voicechat mod

### ISSUE THREAD

**Issue by Ord1naryMan** [henkelmax/replay-voice-chat#13]
**Bug description**
Latest version of mod is not compatible with latest versions of simple voicechat and replaymod on minecraft 1.19.3

**Steps to reproduce the issue**
Use minecraft 1.19.3
Install latest versions of replay mod and simple voicechat mod.

**Expected behavior**
I expect it to work :)

**Log files**

https://gist.github.com/Ord1naryMan/a393bf65f16a81c1fc488f68368506f0

**Versions**
- 1.19.3
- fabrric loader 0.14.14
- voicechat 1.19.3-2.4.8
- replaymod 1.19.3-2.6.11
- simple voiceChat 1.19.3-1.2.4

**Screenshots (Optional)**
![image](https://github.com/henkelmax/replay-voice-chat/assets/111735837/6b3a3721-8b3b-4047-b8eb-49adc503dfa1)

**Comment by henkelmax** [comment]
We only support the latest replay mod version for the latest Minecraft version
