### ISSUE TITLE
Replay voice chat doesn't work in 1.18.2 due to dependency issues,

### ISSUE THREAD

**Issue by netcore10** [henkelmax/replay-voice-chat#15]
We rely on it for our SMP, i understand it's a tall ask - is it possible to fix dependencies on 1.18.2?

![image](https://github.com/henkelmax/replay-voice-chat/assets/181536/6e574539-f201-48b8-a7d7-a38858bc4703)

**Comment by henkelmax** [comment]
We only support the latest version replay mod has been released to.
