### ISSUE TITLE
Truncated or incomplete audio files

### ISSUE THREAD

**Issue by kelticangel** [henkelmax/replay-voice-chat#18]
**Bug description**
A 10 minute and 15 second clip of gameplay that involved several player (at least 8) did not successfully record/render/export usable voice chat audio. Instead, it exported 20 seconds of myself, 40 seconds of another player, and 2 seconds of a third player. Other renders have had similar issues with truncated audio, most being only a few seconds long. 

**Steps to reproduce the issue**
1. Create camera path and render as usual
2. Rendered videos (mp4) function as expected
3. Rendered audio (mp3) files are shortened to a few seconds long

**Expected behavior**
I expected the audio clips to match the video clip in both duration and number of players.

**Log files**
https://gist.github.com/kelticangel/6af8c85d403380a931532ec183aa3365.js

**Versions**
- Minecraft: 1.19.4 (footage was recorded May 20, 2023)
- Fabric version: fabric-api-0.78.0+1.19.4.jar
- Simple Voice Chat version: voicechat-fabric-1.19.4-2.4.4.jar
- ReplayMod Version: replaymod-1.19.4-2.6.12.jar
- Mod version: replayvoicechat-1.19.4-1.3.0.jar

**Other mods**
- lithium-fabric-mc1.19.4-0.11.1.jar
- sodium-fabric-mc1.19.4-0.4.10+build.24.jar
- starlight-1.1.1+fabric.ae22326.jar
- status-1.19.4-1.0.0.jar
- WI-Zoom-Mod-Fabric-1.19.4.jar

I do not believe any of the other mods are likely to interfere with the audio render, but I admit to not attempting a render without other mods. 

**Screenshots (Optional)**
none

**Comment by henkelmax** [comment]
Does this also happen with the latest version of the mod?
Please post proper logs. https://gist.github.com/kelticangel/6af8c85d403380a931532ec183aa3365.js not sure what this is.

**Comment by kelticangel** [comment]
This does happen with replays that are recorded and rendered in the same version. The problem began somewhere between April 22 and May 6. Videos recorded April 22 rendered with no audio problems, videos recorded May 6 rendered with problems. I did not add or change any mods in between recording sessions. 

I have not tried rendering video in a newer version than the recording as I expected that not to work well. Do you recommend trying it?

My apologies for the log, perhaps this link will work.
https://gist.github.com/kelticangel/6af8c85d403380a931532ec183aa3365 
Please let me know if I have misunderstood which logs you need.

**Comment by henkelmax** [comment]
Please check if it works for replays recorded in the same versions.

**Comment by kelticangel** [comment]
Replays rendered in a newer version than recorded has the same issue. Voice chat audio is short (between 7 seconds and 40 seconds long) and it only saved audio from 4 players.

**Comment by henkelmax** [comment]
Did you increase the broadcast range on the server?

**Comment by kelticangel** [comment]
I believe it was left at default settings (32 blocks with fade at 16) but I will check with the person who was running the server and let you know. In the recording I am trying to render, there are 8-10 players within that 32 block radius

**Comment by henkelmax** [comment]
I just tested it with multiple players and a longer recording and everything works fine. Can you check if it works with the latest version for 1.20.1 (We generally don't support older versions)?

**Comment by kelticangel** [comment]
When I tried rendering with a newer version, I was using the latest version (made for 1.20.1).

**Comment by henkelmax** [comment]
And are you 100% sure theres audio missing?
If a player for example talks for 5 seconds and then never says anything again in the recording, it will just be as long as the recording was until that person last said something (to save space and resources).

**Comment by kelticangel** [comment]
The folder with saved audio files only has four short files in it: myself (30 seconds), one of the players I was talking to for the majority of the time (40 seconds), a player who was not involved in the conversation but whose mic picked up noises (7 seconds), and a player who was involved in half on the conversation (about 10 seconds). The scene was a lengthy (10- minute) conversation that involved 4 or 5 active players and lots of negotiation, so none of the audio files are actually usable.  

The audio file for myself, as an example, picked up the moment I was talking to myself as I fell off a cliff-edge en route to the negotiation, and then recorded silence for the remainder of the 30 seconds. It did not record/render any of the actual negotiations.

**Comment by kelticangel** [comment]
Sure, I will do my best

**Comment by kelticangel** [comment]
We've been able to identically reproduce the audio issue on my husband's computer by trying to export the same file. The same 4 (out of 8) audio files were produced of the same players and were identical lengths to the shortened audio files my machine produced. I had been wondering if it could be a memory issue, but I don't think that's the case anymore.

He runs the same mods as I do, plus a few more (like mini-HUD and free cam). His video card is slightly less robust (mine's a GeForce GTX 1650, his is a GTX 1050Ti) and his processor is a little more robust than mine (I have a Ryzen 5 5600, he has a Ryzen 7 5700X) and we have similar RAM (I have 2 sticks of 8GB, he has 1 stick of 16GB). 

Unfortunately, I don't have the man hours to devote to testing incrementally more complex recording scenarios at the moment. Is there a way for me to see if there's some kind of corruption in the .mcpr file? I'm skeptical, because it loads and plays in replay mod without any visible issues, but I figured it was worth asking

**Comment by henkelmax** [comment]
PC specs shouldn't matter here.
Does this also happen with fewer players?

**Comment by henkelmax** [comment]
Closed due to inactivity.

**Comment by kelticangel** [comment]
My apologies, I meant to provide an update. Can this be reopened or should
I start a new one?

Regards,
Beth

https://www.elisabethbellamy.com/

**Comment by henkelmax** [comment]
You can still post your update here. I'll reopen it once I'm able to reproduce it.

**Comment by kelticangel** [comment]
Tested with a different scene from the same recording session. I rendered a 9 min and 44 second clip in which myself and another player collect supplies from our base and then head out to meet up with a third player at spawn. I and the second player are engaged in conversation the entire time. The third player arrives in the last 50 seconds of the recorded clip. 

My audio clip and the seond player's audio clip are 1 minute and 7 seconds long. The third player's audio clip is 9 minutes and 35 seconds long.

**Comment by henkelmax** [comment]
Did you watch the replay before rendering? Is the audio missing in the editor aswell?

**Comment by kelticangel** [comment]
I skipped ahead to the 9-minute mark to place camera and time markers rather than watching through the whole thing. The audio was not missing for the few sections that I did watch. 

I've rendered another one with just myself and a second player, we stayed in proximity for the majority of the 14 minute and 35 second video clip. Our audio clips are both just over 4 mins long and cut off at the same point in the conversation which may be when I skipped ahead to make sure the clip was long enough. 

I suspect I may have watched the first ~5 mins and last ~5 mins of this more recent clip in the editor before rendering, but not the whole thing. I'll try watching all the way through that original clip (with the larger group) in the editor and see if it makes a difference.

**Comment by henkelmax** [comment]
Does this also happen with just recording yourself?

**Comment by kelticangel** [comment]
Unfortunately I rarely talk when I'm alone, so it will be difficult to find a clip but I will look for a section and try that.

Watching through the entire clip in the editor did not fix the audio issue with the larger group. When I tightened up the placement of the time keyframes so that there were fewer instances of individuals moving in and out of proximity (for the same scene), only one player's audio was rendered (the person I was speaking most with) and it is only 1 second long.

**Comment by kelticangel** [comment]
Watching through an entire (10 min and 5 sec) clip in the editor _**did**_ fix the issue when the clip includes just myself and one other player, even when there was a few minutes of silence in the middle. We collected supplies and moved to a new location but did not leave proximity of one another and no one joined us. 

I'm still looking for a clip with just me

**Comment by kelticangel** [comment]
I found a clip when I'm by myself and no one else in proximity. I recorded a 10 min and 16 second section of it; during that scene, I verbally react twice to player deaths in chat: once at 05:08 and again at 10:07 but otherwise was silent. My audio clip rendered properly again this time, with a length of 10:12.

This is frustratingly inconsistent in that it seems to render properly when there are only a few players involved (as long as I watch through the entire clip in the editor first). 
Do you have any further ideas?

**Comment by kelticangel** [comment]
It almost seems as though there are two different issues: 
- watching all the way through in the editor 
- how many players are in close enough proximity to be listed in the "visible players" overview in replay

I'm going to try one more render with time keyframes tightened up even more so that all 8 players are listed in the player overview, and if that still fails then I think I'm going to give up on this issue.

**Comment by kelticangel** [comment]
This time I got a 7 minute and 14 second video clip. The audio of 5 players was rendered but none of them have any actual discernable sound. One of them is 1 second long, two of them are 2 seconds long, and my own and one other player's aren't able to be opened. I've attached a screenshot of the error. 
 
 I'm giving up on this for the moment as I need to prioritize getting some kind of completed video out. However, I'm definitely concerned about this issue going forward. 

![Screenshot 2023-07-11 162116](https://github.com/henkelmax/replay-voice-chat/assets/29667061/180d59da-3f7a-42c1-86d7-faad1367f4d5)

**Comment by henkelmax** [comment]
Alright, reproducing this will not be easy if multiple players are needed. I will look into it though.

**Comment by kelticangel** [comment]
I'll send you the file I've been playing with. The specific scene with 8-9 people begins at the event marker (~83 mins in) at coordinates 262 and -56, if you want to look at it in the editor. 

This is a link to the zipped file: https://mega.nz/file/nu4zhQAZ#jpr33BbTPmNcYiwANQhrfRXOTn-az4uhPIKkKFPazuo

**Comment by henkelmax** [comment]
Thank you for providing me the replay @kelticangel. I managed to reproduce your issue in that timeframe and location.

**Comment by henkelmax** [comment]
I found the issue. It was an unhandled error that occurs when a player that is talking logs out. That corrupts the recording at the point of the error. I'll let you know once the fixed version is released.

Again, thank you for providing me with all the useful information and helping me finding out the cause!

Now all audio files have the correct length:
![image](https://github.com/henkelmax/replay-voice-chat/assets/13237524/e3b8eebe-1c38-45cf-8154-5a2b21c8cb3d)

**Comment by henkelmax** [comment]
Alright, the update is published for 1.19.2, 1.19.4 and 1.20.1 on CurseForge and Modrinth.
Thanks again @kelticangel!

**Comment by kelticangel** [comment]
Thank you!
