### ISSUE TITLE
Update/backport Replay Voice Chat to 1.20

### ISSUE THREAD

**Issue by byxea** [henkelmax/replay-voice-chat#19]
- Minecraft version: 1.20
- Fabric version: 0.14.21
- Fabric API: 0.83.0+1.20
- Simple Voice Chat version: 1.20-2.4.9
- ReplayMod Version: 1.20.1-2.6.13
**Bug description**
Game crashes on 1.20 with this error message:

```
A potential solution has been determined:
	 - Replace mod 'Replay Voice Chat' (replayvoicechat) 1.20.1-1.3.2 with any version that is compatible with:
		 - minecraft 1.20
		 - voicechat 1.20-2.4.9
```

**Steps to reproduce the issue**
1. Install latest version of [Simple Voice Chat](https://modrinth.com/plugin/simple-voice-chat/version/fabric-1.20-2.4.9) and [ReplayMod](https://modrinth.com/mod/replaymod/version/1.20.1-2.6.13) for 1.20 with the latest version of [Replay Voice Chat](https://modrinth.com/mod/replay-voice-chat/version/fabric-1.20.1-1.3.2) available from Modrinth.
2. Launch the game.
3. Game crashes with error.

**Expected behavior**
Game launches, and works fine.

**Log files**
[https://mclo.gs/j7s2rId](https://mclo.gs/j7s2rId)

**Versions**
- Minecraft version: 1.20
- Fabric version: 0.14.21
- Fabric API: 0.83.0+1.20
- Simple Voice Chat version: 1.20-2.4.9
- ReplayMod Version: 1.20.1-2.6.13
- Replay Voice Chat version: 1.20.1-1.3.2

**Other mods**

- Replay Voice Chat
- Fabric API
- Simple Voice Chat
- Replay Mod

**Comment by henkelmax** [comment]
Sorry, but we will only support the latest Minecraft version, ReplayMod has been released to.
