### ISSUE TITLE
Rendering Audio

### ISSUE THREAD

**Issue by FC-Creations** [henkelmax/replay-voice-chat#2]
In the features list it mentions rendering audio in separate channels. It doesn't seem to be rendering audio at all? I can still use it by recording the audio with OBS which is cool, but your features list leads me to believe audio should be rendering!

Let me know if you need any info from me, if this is a bug! I'll be happy to help!

**Comment by henkelmax** [comment]
Oh, sorry for the inconvenience. The templates haven't het been set up.

The rendered audio is put in a separate folder named the same as the video file.

**Comment by FC-Creations** [comment]
Thank you, yeah I found the folders, I felt so dumb!

Do you think it's within the realm of possibility to use a similar method to extract in-game sounds as well? Or is this only possible because of how the audio from simple voice is stored?

**Comment by henkelmax** [comment]
There is no possibility to capture audio from an OpenAL source. We use a hacky workaround in Simple Voice Chat...
Moreover, this would lie in the realm of the ReplayMod developers to implement.

**Comment by FC-Creations** [comment]
No, you're right. I wasn't specifically asking for YOU to do it, just to see if you had any insight in case someone, possibly myself, might consider taking the time to create a plugin that would be able to render in-game audio.  

Thanks for your time, and thanks for all your hard work with these plugins!
