### ISSUE TITLE
Replay Voice Chat calls for significantly older versions of Replaymod and Simple Voice Chat on 1.19.3 build. 

### ISSUE THREAD

**Issue by Aeraki** [henkelmax/replay-voice-chat#20]
**Bug description**
Essentially it is calling for versions of replaymod and SVC significantly older than what it should be, causing incompatibly on servers if used. 

**Steps to reproduce the issue**
1. Go to 'Install replay voice chat 1.19.3'
2. Launch game
3. Game crash
4. See error; It wants you to install extremely old versions of both replaymod (calls for 1.19.3-2.6.10, latest verson for 1.19.3 is 1.19.3-2.6.13) and simple voice chat (calls for any version before 1.19.3-2.4.0, latest version is 1.19.3-2.4.8).

**Expected behavior**
Expected behavior is that the mod will call for the latest versions of both Replaymod and SVC. 
**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue.
(https://gist.github.com/Aeraki/bb0691bfe0c8966e4e330b6e5b0b6e39)

**Versions**
- 1.19.3
- Fabric version 0.14.21-1.19.3
- Simple Voice Chat version 1.19.3-2.4.8
- ReplayMod Version 1.19.3-2.6.13
- Mod version 1.19.3-1.2.4

**Other mods**
Other mods installed do not effect this error.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
We only support the latest Minecraft version, ReplayMod is released for.
