### ISSUE TITLE
Version incompatibility on 1.19.2

### ISSUE THREAD

**Issue by SpaceBrandCereal** [henkelmax/replay-voice-chat#21]
Simply launch the game with replay voice chat and replay mod with both of them being the latest version on 1.19.2 and this will show up
![image_2023-07-13_210650086](https://github.com/henkelmax/replay-voice-chat/assets/139027678/038cf213-4bcb-4b6a-990a-d2440cb98604)

**Comment by henkelmax** [comment]
You are using an outdated version.

**Comment by SpaceBrandCereal** [comment]
Those are the latest versions of both mods. If you're talking about the minecraft version 1.19.2 is hardly outdated and, if you say it's outdated because you're mod doesn't work with it, then why would you let people on curseforge download the mod for 1.19.2?

**Comment by henkelmax** [comment]
https://modrinth.com/mod/replay-voice-chat/version/fabric-1.19.2-1.3.3

**Comment by SpaceBrandCereal** [comment]
Still doesn't work.

**Comment by henkelmax** [comment]
Then fill out the bug template.
