### ISSUE TITLE
Not compatible with Replay 2.6.14 on 1.20.1

### ISSUE THREAD

**Issue by Josh65-2201** [henkelmax/replay-voice-chat#24]
**Bug description**
![image](https://github.com/henkelmax/replay-voice-chat/assets/26977075/65c267eb-aad8-42dc-8393-bf8877f8a26a)

**Steps to reproduce the issue**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue.
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Simple Voice Chat version: 2.4.32
- Minecraft version: 1.20.1
- Fabric loader version: Quilt 0.22
- ReplayMod Version: 2.6.14
- Mod version: 1.3.3

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Only the latest Minecraft version is actively supported.
