### ISSUE TITLE
Editing (slitting and cutting) replays with replay voice mod causes crash

### ISSUE THREAD

**Issue by Tm4lg** [henkelmax/replay-voice-chat#26]
**Bug description**
As above. Using MacOS Ventura and Minecraft 1.20.1. Is editing replay files currently a supported feature?

**Comment by henkelmax** [comment]
Please fill out the full bug template. We also only provide support for the latest Minecraft version, ReplayMod is released for.
So please check if it still happens for that version and open a ticket with all requested details provided.
