### ISSUE TITLE
Problem with mod dependency in version 1.18.2

### ISSUE THREAD

**Issue by seriousfreezing** [henkelmax/replay-voice-chat#27]
I'm having a problem where I need to use an older version of Replay mod and Simple Voice Chat to be able to use Replay Voice Chat.

Can I remove these dependencies via fabric_loader_dependencies.json? Or what could you suggest as a workaround?

**Comment by henkelmax** [comment]
We only support the latest minecraft version, replay mod is released to. if you want to override the restrictions use https://fabricmc.net/wiki/tutorial:dependency_overrides but it will most certainly break.
