### ISSUE TITLE
Version strange error

### ISSUE THREAD

**Issue by an1by** [henkelmax/replay-voice-chat#29]
### Bug description

Version error on starting Fabric Loader with mod.

### Minecraft version

1.20.1

### Simple Voice Chat version

1.20.1-2.5.0

### ReplayMod version

1.20.1-2.6.13

### Mod version

1.20.1-1.3.3

### Mod loader and version

Fabric Loader 0.14.22

### Steps to reproduce

1. Download & install all mods and fabric loader
2. Start the game

### Log files

https://gist.github.com/an1by/7db8a332a040fd42566d0f6f397fa727

### Screenshots

![image](https://github.com/henkelmax/replay-voice-chat/assets/61041788/2a9e8774-b6f1-41d6-a7c7-97565667f7e2)

**Comment by henkelmax** [comment]
The message you are seeing should be descriptive enough.
