### ISSUE TITLE
Rendered audio cutting out at moments that it doesn't in the in game replay

### ISSUE THREAD

**Issue by JimGringo** [henkelmax/replay-voice-chat#30]
### Bug description

After grabbing a clip from replay mod that has perfectly good audio from simple voice chat, I rendered the clip using and brought it into davinci, but the audio now has breaks and pauses in a ton of places that the original did not have. I have noticed that in the logs it seems to talk about overlapping with previous snippet but i am not sure if that is apart of it.

### Minecraft version

1.20.4

### Simple Voice Chat version

1.20.4-2.5.4

### ReplayMod version

1.20.4-2.6.14

### Mod version

1.20.4-1.3.5

### Mod loader and version

Fabric Loader 0.15.7

### Steps to reproduce

Record a clip using replay mod, speak for a bit using simple voice chat, get the section of you speaking and render that out with ffmpeg installed. Bring it into a video editor of your choice and place the audio and just listen.

### Expected behavior

Audio to be clear

### Log files

https://gist.github.com/JimGringo/6cfaab73dc281ce1b3217017750e67a6

**Comment by henkelmax** [comment]
Do you have an example replay file where this is happening?

**Comment by JimGringo** [comment]
https://drive.google.com/file/d/1hqDArRjoQpsnFTZsuvSMfn0AoQRD6h7O/view?usp=sharing
We used bobby on the camera which is why im assuming the file is so large, but yeah if you play the rendered audio after the replay file you can almost immediately hear the difference.

**Comment by henkelmax** [comment]
I unfortunately can't open that replay file, since you are using other mods that make it incompatible.
What happens if you export the same recording again? does it sound exactly the same?

**Comment by JimGringo** [comment]
Yeah, this is probably the 10th export of the same clip with the same result. I've tried to recreate it in different circumstances without any luck. I think have found the issue though, the person recording this has a terrible pc, when testing from specifically that computer the exports are bad, so I guess thats the issue solved, idk if you want to close this.
