### ISSUE TITLE
Incompatibility of Replay Voice Chat with Chat Patches

### ISSUE THREAD

**Issue by MacroVoid** [henkelmax/replay-voice-chat#32]
### Bug description

When watching the replay and Chat Patches are installed, the players do not have a voice, but the icons are displayed. I tried different versions of Simple Voice Chat (1.20.1-2.4.16 and 1.20.1-2.4.32), but it didn't help. The problem is that the output device becomes unavailable. Chat Patches Version: 201.5.5
![image](https://github.com/henkelmax/replay-voice-chat/assets/166911580/a0d98fee-8b8f-4e47-8ef4-3af9ec44620f)

### Minecraft version

1.20.1

### Simple Voice Chat version

1,20.1-2.4.16

### ReplayMod version

1.20.1-2.6.13

### Mod version

1.20.1-1.3.3

### Mod loader and version

Fabric Loader 0.15.7

### Steps to reproduce

1) Install the Replay Voice Chat and Chat Patches mods 2) Start watching replay 3) Do not detect the sound of Simple Voice Chat

### Expected behavior

I want to see the main function of the mod working - to play sound in replays

### Log files

https://gist.github.com/MacroVoid/cac28eece9d28f9a09398a6ac3354bb9

**Comment by henkelmax** [comment]
You are using an outdated voice chat and replay voice chat version.

**Comment by henkelmax** [comment]
The error in your logs also shows an error with chat patches. so this is most likely an issue of the chat patches mod. please report it there.
