### ISSUE TITLE
Latest 1.20.1 Replay Voice Chat Mod incompatible with latest 1.20.1 Voice Chat Mod

### ISSUE THREAD

**Issue by LetaStar** [henkelmax/replay-voice-chat#35]
### Bug description

The latest versions for both mods in 1.20.1 won't work together 

### Minecraft version

1.20.1

### Simple Voice Chat version

1.20.1-2.5.14

### ReplayMod version

1.20.1-2.6.13

### Mod version

1.20.1-1.3.3

### Mod loader and version

Fabric Loader 0.15.10

### Steps to reproduce

1 Install the specified versions
2 Open Minecraft
3 Recieve error listed in screenshot

### Log files

https://gist.github.com/LetaStar/9cf8c0ca1b048985f371a08bd408fff0

### Screenshots

![image](https://github.com/henkelmax/replay-voice-chat/assets/69783691/7648261d-9d45-4f47-8cd8-f7862ed14223)

**Comment by henkelmax** [comment]
930724cae6f1bc49c004107201499ea748e494d5
