### ISSUE TITLE
Replay Voice Chat dosent work in the Version 1.20.1

### ISSUE THREAD

**Issue by DasVanish** [henkelmax/replay-voice-chat#36]
### Bug description

Maybe am i doing something wrong but if i try to load up the Replay, Simple Voice Chat and the replay voice chat it does not work because of incompatible Mods. I tried to switch the versions of the Mods but i didnt work aswell. 

The Error:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Replay Voice Chat' (replayvoicechat) 1.20.1-1.3.3 with any version that is compatible with:
		 - voicechat 1.20.1-2.5.15
More details:
	 - Mod 'Replay Voice Chat' (replayvoicechat) 1.20.1-1.3.3 is incompatible with version 1.20.1-2.5.0 or later of mod 'Simple Voice Chat' (voicechat), but a matching version is present: 1.20.1-2.5.15!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Do u guys know this Issue or did i something wrong?

Thanks for Helping and a good rest of the day!

### Minecraft version

1.20.1

### Simple Voice Chat version

1.20.1-2.5.15

### ReplayMod version

1.20.1-2.6.13

### Mod version

1.20.1-1.3.3

### Mod loader and version

Fabric-0.15.11 (Curseforge)

### Steps to reproduce

Put the 3 Mods in a Modpack on Curseforge with the same Fabric version and try to start it.

### Expected behavior

A window with the Error copied above will open

### Log files

https://gist.github.com/DasVanish/9511f539c77881025253093dd1afffb2

### Screenshots

![error](https://github.com/henkelmax/replay-voice-chat/assets/143296187/667c1a48-fc78-459c-b682-f2f72d03a672)

**Comment by henkelmax** [comment]
As your screen already states. The version of replay voice chat and simple voice chat aren't compatible. This is not a bug.

**Comment by DasVanish** [comment]
Ok than im sorry, but can you Tell me wich Version compatible is?

**Comment by henkelmax** [comment]
Everything older than 2.5

**Comment by AftDawn** [comment]
are you going to make the mod work with 2.5?

**Comment by henkelmax** [comment]
Replay Voice Chat will only be updated for the latest version of replaymod. If thats an issue for you, you can always port the mod yourself.
