### ISSUE TITLE
voice doesnt record

### ISSUE THREAD

**Issue by zhigulevskoe** [henkelmax/replay-voice-chat#37]
### Bug description

the mod is visible in mod menu, it doesct create any issues in logs. but when i open replay i cant hear anybody. mute icons are showed near the nickname but talking icons doesnt

### Minecraft version

1.20.4

### Simple Voice Chat version

1.20.4-2.5.26

### ReplayMod version

1.20.4-2.6.15

### Mod version

1.20.4-1.3.7

### Mod loader and version

Fabric Loader 0.15.11

### Steps to reproduce

sorry but i dont know what to write there...

### Log files

https://drive.google.com/file/d/19_QcKhQFldiHRIOK7UEsa7ZjXyFfC3QB/view?usp=drive_link

**Comment by zhigulevskoe** [comment]
sorry if i did smth wrong in my bug report. i dont exactly know what to do because another replay mod addon-replay fps-doesnt work too... its simply dont wanna do anything harder than existing and being visible in mod menu

**Comment by henkelmax** [comment]
This Minecraft/Mod version is no longer supported, sorry.

**Comment by zhigulevskoe** [comment]
I dont understand. Why is 1.20.4 version of this mod exists if it is doesnt work on 1.20.4

**Comment by henkelmax** [comment]
All I said is that this version is no longer actively developed and supported.
