### ISSUE TITLE
1.20.6 support

### ISSUE THREAD

**Issue by KarmaMarazu** [henkelmax/replay-voice-chat#38]
### Bug description

is there any plans to add support for replay voice mod for 1.20.6? i tried changing the dependencies for the 1.21 version to make it work sadly i got a crash (as i expected) are there any plans to support it? if not feel free to close the issue

### Minecraft version

1.20.6

### Simple Voice Chat version

-

### ReplayMod version

-

### Mod version

-

### Mod loader and version

Fabric Loader 0.15.11

### Steps to reproduce

-

### Log files

https://mclo.gs/3aL36WG

**Comment by henkelmax** [comment]
Only the latest minecraft version replaymod is released to is supported.
