### ISSUE TITLE
Question about PlasmoVoice

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [henkelmax/replay-voice-chat#4]
Will this mod work with PlasmoVoice? (Because we use PlasmoVoice on our server)
P.S. Why is there only Bug label lmfao

**Comment by MrMasrozYTLIVE** [comment]
Bruh... It also auto assigned you guys, sorry lmfao

**Comment by henkelmax** [comment]
The plasmo guys forked the mod and made it compatible with their mod, but this one doesn't work with plasmo.

**Comment by henkelmax** [comment]
> oof
> 

?
