### ISSUE TITLE
The voice recordings are not complete

### ISSUE THREAD

**Issue by shinenyugen** [henkelmax/replay-voice-chat#5]
I use replay voice chat with replaymod on fabric 1.19 with sodium in a multiplayer server. 

I recorded some footage with replaymod, and rendered it. The rendered video is 23 minutes long but the audio recordings are each between 8 - 9 minutes. Every player has different amount of time and it only picked up the players that were online at the start of the recording the rest of the players don't have a recorded audio file. My own audio file it's also about 8-9 minutes. It's my first time using the replay voice chat and I expected that each player would have an audio file and it would be recorded from the moment they join until the recording ends even if they don't talk or are muted in between

**Comment by henkelmax** [comment]
Please fill out the bug template and provide logs
