### ISSUE TITLE
 Replay Voice Chat 1.19.2-1.2.3 requires version 1.19.2-2.6.9 of Replay Mod

### ISSUE THREAD

**Issue by ClaudiusMinimus** [henkelmax/replay-voice-chat#8]
Unable to have both Replay Voice Chat 1.19.2-1.2.3 and Replay Mod 1.19.1-2.6.10 run together. The error is asking for Replay Mod 1.19.2-2.6.9, which is not available on CurseForge.

Minecraft 1.19.2
Fabric 0.14.12 - Just updated to 0.14.13 makes no difference
```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Replay Mod' (replaymod) 1.19.1-2.6.10 with version 1.19.2-2.6.9.
Unmet dependency listing:
	 - Mod 'Replay Voice Chat' (replayvoicechat) 1.19.2-1.2.3 requires version 1.19.2-2.6.9 of mod 'Replay Mod' (replaymod), but only the wrong version is present: 1.19.1-2.6.10!
```
![image](https://user-images.githubusercontent.com/17887664/215239388-f7c7bcdf-a680-4e83-ada9-1511b4979580.png)

**Comment by henkelmax** [comment]
Update the mod to the latest version.

**Comment by ClaudiusMinimus** [comment]
I installed the latest versions of Replay Voice Chat for **Minecraft 1.19.2**, which is version 1.19.2-1.2.3.The only update newer is for Minecraft 1.19.3 and is **not compatible** with Minecraft 1.19.2 and is not available in GDLauncher or Prism for 1.19.2 and Fabric 0.14.13 (see screenshots).

I am not trying to be difficult, but if you will look at this detailed issue report, then you will see the problem is with the mod, not me. Many of the mods in my pack have not been ported to Minecraft 1.19.2, which is why I have not upgraded to 1.19.3. Regardless, if you can provide me a link to a later version than what is shown, then I will use it.

However, it seems to there are three choices:
1.Since Replay Voice Chat 1.19.2-1.2.3 is the newest version compatible with **Minecraft 1.19.2**, a  new Replay Voice Chat 1.19.2-1.2.4 might in order.
2. Make Replay Voice Chat 1.19.3-1.2.4 compatible with **Minecraft 1.19.2**
3. Ask the developer for Replay Mod to make version 1.19.2-2.6.9 available on CurseForge, though this is the least desirable since newer versions hopefully address bugs.
4.  Tell me a fix is coming or you are no longer supporting Minecraft 1.19.2.

Finally, please do not dismiss me and just say to upgrade.

Thank you!
CM

**Json from `fabric.mod.json` Starting Line 31 - extracted from `replayvoicechat-1.19.2-1.2.3.jar`**
```json
  "depends": {
    "fabricloader": "\u003e\u003d0.14.8",
    "minecraft": "1.19.2",
    "java": "\u003e\u003d17",
    "voicechat": "\u003e\u003d1.19.2-2.3.4",
    "replaymod": "\u003d1.19.2-2.6.9"
```
**Json from `fabric.mod.json` Starting Line 31 - extracted from `replayvoicechat-1.19.3-1.2.4.jar`**
```json
    "depends": {
      "fabricloader": "\u003e\u003d0.14.10",
      "minecraft": "1.19.3",
      "java": "\u003e\u003d17",
      "voicechat": "\u003e\u003d1.19.3-2.3.19",
      "replaymod": "\u003d1.19.3-2.6.10"
```
![image](https://user-images.githubusercontent.com/17887664/215254288-03bfa34c-a986-4d3b-9536-8df7a8c18229.png)
![image](https://user-images.githubusercontent.com/17887664/215254382-ff2ed350-c58a-48c4-bd63-bfa23cc438f9.png)
![image](https://user-images.githubusercontent.com/17887664/215254323-242636bb-e050-4e9d-bf64-ef5d8d08b2f1.png)
![image](https://user-images.githubusercontent.com/17887664/215254358-b1c8290f-ea58-4230-94eb-98dde801945e.png)

**Comment by henkelmax** [comment]
Oh sorry, I didn't see that you were using 1.19.2 
I only maintain compatibility with the latest replay mod version on the latest minecraft release.

**Comment by ClaudiusMinimus** [comment]
Thanks for letting me know. I guess I'll just edit the fabric.mod.json and hope it works.
Cheers!
